import '../model/tip/tip.dart';

Map<Tip, List<String>> tips = {
  Tip.time: [
    "Set goals. What do you want to achieve? Once you know your goals, you can start to plan how you will achieve them.",
    "Make a schedule. Break down your goals into smaller tasks and assign them a time frame. Be realistic about how much time you have and what you can accomplish in a given amount of time.",
    "Prioritize your tasks. Not all tasks are created equal. Some tasks are more important than others. Decide which tasks are most important and focus on those first.",
    "Eliminate distractions. When you are trying to focus on a task, it is important to eliminate distractions. This means turning off your phone, closing your email, and finding a quiet place to work.",
    "Take breaks. It is important to take breaks when you are working on a task. This will help you stay focused and refreshed.",
    "Delegate tasks. If you have too much on your plate, it is important to delegate tasks to others. This will free up your time so that you can focus on the most important tasks",
    "Use technology. There are many technology tools that can help you organize your time. For example, you can use a calendar to keep track of your appointments, a to-do list to keep track of your tasks, and a project management tool to track the progress of your projects.",
    "Be flexible. Things don't always go according to plan. Be prepared to adjust your schedule as needed.",
    "Don't be afraid to say no. It is important to learn how to say no to requests that will take up too much of your time.",
    "Reward yourself. When you complete a task, reward yourself for your accomplishment. This will help you stay motivated.",
    "Get enough sleep. When you are well-rested, you will be better able to focus and organize your time.",
    "Eat healthy foods. Eating healthy foods will give you the energy you need to focus and be productive.",
    "Exercise regularly. Exercise has been shown to improve cognitive function and reduce stress.",
    "Take care of yourself. Make time for activities that you enjoy and that help you relax.",
    "Don't be afraid to ask for help. If you are struggling to organize your time, don't be afraid to ask for help from a friend, family member, or professional."
  ],
  Tip.selfCare: [
    "Get enough sleep. Most adults need around 7-8 hours of sleep per night. When you're well-rested, you'll have more energy and be better able to focus on your day.",
    "Eat healthy foods. Eating nutritious foods will give you the energy you need to get through the day. Make sure to eat plenty of fruits, vegetables, and whole grains.",
    "Exercise regularly. Aim for at least 30 minutes of moderate-intensity exercise most days of the week. Exercise has been shown to improve mood, reduce stress, and boost energy levels.",
    "Manage stress. Find healthy ways to cope with stress, such as yoga, meditation, or spending time in nature.",
    "Spend time with loved ones. Social connection is important for your mental and physical health. Make time to connect with friends and family on a regular basis.",
    "Get a massage. Massage can help to relieve stress, muscle tension, and pain.",
    "Take a break from technology. Give yourself a break from screens each day. Spend some time outdoors, read a book, or listen to music.",
    "Do something you enjoy. Make sure to schedule time for activities that you enjoy, whether it's reading, listening to music, or spending time outdoors.",
    "Get creative. Express yourself creatively through activities such as painting, writing, or playing music.",
    "Get organized. Organizing your home and workspace can help to reduce stress and make you feel more in control.",
    "Practice gratitude. Take some time each day to reflect on the things you're grateful for. This can help to improve your mood and outlook on life.",
    "Say no to things that you don't have time for. It's okay to say no to requests that will take up too much of your time.",
    "Learn to forgive yourself. Everyone makes mistakes. Don't dwell on your past mistakes. Learn from them and move on.",
    "Take care of your physical health. Make sure to get regular checkups and see your doctor if you're not feeling well.",
    "Take care of your mental health. If you're struggling with your mental health, don't hesitate to seek professional help.",
    "Set boundaries. It's important to set boundaries with others, such as not checking work email after hours.",
    "Delegate tasks. If you have too much on your plate, don't be afraid to ask for help. Delegate tasks to others who can help you out.",
    "Take breaks throughout the day. Get up and move around every 20-30 minutes to avoid getting too tired or stressed.",
    "Drink plenty of water. Staying hydrated is important for your physical and mental health.",
    "Eat regular meals and snacks. Don't skip meals or snacks. This can lead to low blood sugar and make you feel tired and irritable.",
    "Listen to your body. Pay attention to your body's signals. If you're tired, take a nap. If you're hungry, eat a snack.",
    "Don't compare yourself to others. Everyone is different. Focus on your own journey and don't worry about what others are doing.",
    "Be kind to yourself. Treat yourself with kindness and compassion. You deserve it!",
    "Practice self-care every day. Self-care is not just about doing things you enjoy. It's also about taking care of your physical and mental health. Make time for self-care every day, even if it's just for a few minutes.",
  ],
  Tip.collage: [
    "Attend classes and participate in discussions. This is the most important thing you can do to succeed in college. Pay attention to the lectures, take notes, and ask questions. Participating in discussions will help you to learn the material better and make connections with your classmates and professors.",
    "Complete all of your assignments. This includes homework, quizzes, exams, and papers. Don't procrastinate and start working on your assignments early.",
    "Seek help when you need it. Don't be afraid to ask for help from your professors, teaching assistants, or tutors. There are also many resources available online and on campus to help you with your studies.",
    "Manage your time effectively. College can be a lot of work, so it's important to manage your time wisely. Create a schedule and stick to it. Make sure to schedule time for studying, attending classes, socializing, and relaxing.",
    "Develop healthy study habits. Find a study spot that works for you and stick to it. Avoid distractions like your phone, TV, and social media. Take breaks often and reward yourself for your hard work.",
    "Get enough sleep. Most adults need around 7-8 hours of sleep per night. When you're well-rested, you'll be able to focus better in class and retain more information.",
    "Eat healthy foods. Eating nutritious foods will give you the energy you need to study and focus. Make sure to eat plenty of fruits, vegetables, and whole grains.",
    "Exercise regularly. Aim for at least 30 minutes of moderate-intensity exercise most days of the week. Exercise has been shown to improve mood, reduce stress, and boost energy levels.",
    "Get involved in campus life. There are many clubs, organizations, and events on campus that you can get involved in. This is a great way to meet new people, make friends, and learn new things.",
    "Take care of your mental health. College can be stressful, so it's important to take care of your mental health. Find healthy ways to cope with stress, such as yoga, meditation, or spending time in nature.",
    "Don't compare yourself to others. Everyone is different, so don't compare yourself to your classmates. Focus on your own progress and goals.",
    "Set realistic expectations. College is a lot of work, so don't expect to get straight A's. Set realistic expectations for yourself and celebrate your accomplishments along the way.",
    "Be patient with yourself. It takes time to adjust to college life. Don't get discouraged if you don't get it right away. Just keep working hard and you will eventually succeed.",
    "Find a mentor. A mentor can be a valuable resource for guidance and support. They can help you with your studies, career planning, and personal development.",
    "Get involved in research or internships. This is a great way to gain experience in your field and make yourself more marketable to future employers.",
    "Network with professionals in your field. Attend industry events, meet with alumni, and connect with people on LinkedIn.",
    "Take advantage of career services. Your college likely has a career services center that can help you with your job search. They can help you write your resume, prepare for interviews, and find job openings.",
    "Don't be afraid to take risks. College is a time to experiment and try new things. Don't be afraid to step outside of your comfort zone and try something new.",
    "Have fun! College is a great time to learn, grow, and make memories that will last a lifetime. Don't forget to have fun along the way!",
    "Be respectful of others. Treat your classmates, professors, and other members of the college community with respect.",
    "Be responsible for your actions. Take responsibility for your choices and actions. Don't blame others for your mistakes.",
    "Be honest and ethical. Always tell the truth and do the right thing.",
    "Be open-minded. Be willing to learn new things and consider different perspectives.",
    "Be grateful for your opportunities. College is a privilege, so be grateful for the opportunity to learn and grow.",
    "Believe in yourself. You are capable of achieving great things. Believe in yourself and never give up on your dreams.",
  ],
  Tip.study: [
    "Set realistic goals. Don't try to cram everything in at once. Break down your studies into manageable chunks and set deadlines for yourself.",
    "Find a quiet place to study. Free from distractions like TV, music, and social media.",
    "Take breaks. Studying for long periods without breaks can be counterproductive. Get up and move around every 20-30 minutes.",
    "Find a study method that works for you. Some people prefer to study by reading, while others prefer to listen to lectures or watch videos. Experiment with different methods to find what works best for you.",
    "Use flashcards. Flashcards are a great way to memorize information.",
    "Create mind maps. Mind maps are a visual way to organize information.",
    "Practice active recall. Active recall is the process of trying to remember information without looking at it. This can be done by answering questions, summarizing what you've learned, or teaching someone else.",
    "Get enough sleep. Sleep is essential for memory consolidation. Aim for 7-8 hours of sleep per night.",
    "Eat healthy foods. Eating healthy foods will give you the energy you need to focus.",
    "Exercise regularly. Exercise has been shown to improve cognitive function.",
    "Find a study buddy or group. Studying with others can help you stay motivated and on track.",
    "Reward yourself for your accomplishments. Celebrating your successes will help you stay motivated.",
    "Don't be afraid to ask for help. If you're struggling with a particular concept, don't be afraid to ask your teacher, tutor, or classmate for help.",
    "Use technology to your advantage. There are many great apps and websites that can help you study.",
    "Take advantage of your school's resources. Many schools offer tutoring, study groups, and other resources to help students succeed.",
    "Don't procrastinate. Procrastination can lead to stress and anxiety. Start studying early and avoid cramming at the last minute.",
    "Believe in yourself. You are capable of achieving your goals.",
    "Don't be afraid to fail. Failure is a part of the learning process. Don't let it discourage you.",
    "Learn from your mistakes. Reflect on what went wrong and how you can do better next time.",
    "Set realistic expectations for yourself. Don't expect to get perfect grades on everything.",
    "Find a balance between schoolwork and other activities. It's important to have a life outside of school. Make time for hobbies, friends, and family.",
    "Manage your stress. Find healthy ways to cope with stress, such as exercise, relaxation techniques, or spending time with loved ones.",
    "Don't compare yourself to others. Everyone learns at their own pace.",
    "Be patient with yourself. It takes time to learn new things.",
    "Celebrate your successes. Take pride in your accomplishments, no matter how big or small.",
    "Don't give up. Keep working hard and you will eventually reach your goals.",
  ],
};
